import React, { useEffect, useState } from "react"
import Records from './Records'


const Fetcher = () => {
    const [records, setRecords] = useState([{}])

    let auxRecords = {
        "Records": [
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "10 Day Pass",
                "Description": "10 full days at Kalkio Space.",
                "InvoiceLineDisplayAs": "",
                "Sku": "",
                "Tags": "day passes",
                "DisplayOrder": 0,
                "Price": 330,
                "Visible": true,
                "SyncToSquare": true,
                "CurrencyId": 3005,
                "CurrencyCode": "GBP",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1414911424,
                "AvailableAs": 2,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": -107,
                "StockAlertLevel": 15,
                "InvoiceCoworker": true,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": "s906228543484981547_p8_i1_w300[1].png",
                "ClearImageFile": false,
                "Id": 1004438440,
                "UpdatedOn": "2022-11-08T17:44:45Z",
                "CreatedOn": "2019-04-28T17:26:44Z",
                "UniqueId": "1abc1efe-7541-46da-a603-b81512aa5e0a",
                "UpdatedBy": "isabelle+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": "DEMO",
                "ToStringText": "10 Day Pass (330.00 GBP)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161924,
                "BusinessName": "Kalkio Network",
                "Name": "10 Network Day Passes",
                "Description": "10 days of access at any of our locations.",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 250,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": false,
                "CurrentStock": 5,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1358309961,
                "UpdatedOn": "2022-08-30T09:05:48Z",
                "CreatedOn": "2020-07-27T13:50:09Z",
                "UniqueId": "3becc0e5-ee68-4c55-a0e7-5fa787425650",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "10 Network Day Passes (250.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161925,
                "BusinessName": "Kalkio Office",
                "Name": "100 hours package",
                "Description": "100 hours package 2",
                "InvoiceLineDisplayAs": "100 hours package",
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": true,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1196519325,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1103539437,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415016069,
                "UpdatedOn": "2022-09-15T14:13:15Z",
                "CreatedOn": "2022-05-15T18:34:59Z",
                "UniqueId": "99563d93-fee4-4944-8093-3f20a5a98d2b",
                "UpdatedBy": "isabelle+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "100 hours package (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "A Product",
                "Description": "This credit will allow you to book one personal training session in the gym. \n\nAll credits purchased and sessions booked are subject to the terms of your agreement with 79 Borough Road Limited (trading as the Ministry) including the PT Product Rules.12345",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": 0,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415039524,
                "UpdatedOn": "2022-10-13T20:42:18Z",
                "CreatedOn": "2022-09-02T13:48:25Z",
                "UniqueId": "8b48326b-8f2b-436b-963e-79ab20bc003d",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "A Product (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "B&W Printing",
                "Description": "Printing for eZeep ",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": 0,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415039630,
                "UpdatedOn": "2022-10-29T06:17:13Z",
                "CreatedOn": "2022-09-02T10:59:02Z",
                "UniqueId": "896835fe-42f8-424b-96ae-cc62760d4300",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "B&W Printing (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161925,
                "BusinessName": "Kalkio Office",
                "Name": "Black and White Print",
                "Description": "Black and White Print",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0.1,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1362793432,
                "UpdatedOn": "2022-03-03T11:59:04Z",
                "CreatedOn": "2020-08-03T10:53:55Z",
                "UniqueId": "32a84ef0-32bf-47d2-a03d-3e66b73e3272",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Black and White Print (0.10 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "buenos dias proyecto",
                "Description": "buenos dias proyecto",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": true,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": true,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": true,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415029275,
                "UpdatedOn": "2022-07-13T08:19:12Z",
                "CreatedOn": "2022-07-13T08:16:58Z",
                "UniqueId": "6a217eb5-8b08-4224-b952-bcf2c65758f9",
                "UpdatedBy": "adrian+1004930927@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "buenos dias proyecto (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Catering Service",
                "Description": "Catering Service",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": "Services",
                "DisplayOrder": 0,
                "Price": 10,
                "Visible": true,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1067467401,
                "ReducedTaxRateId": 1196519325,
                "ExemptTaxRateId": 1106436339,
                "FinancialAccountId": 1027679653,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": true,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": -56,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": "asiya-kiev-SiwrpBnxDww-unsplash.jpg",
                "ClearImageFile": false,
                "Id": 1006547544,
                "UpdatedOn": "2022-08-23T20:37:33Z",
                "CreatedOn": "2019-04-29T17:05:51Z",
                "UniqueId": "abcd29f4-2024-4bdc-975f-a6d773c66da1",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Catering Service (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161925,
                "BusinessName": "Kalkio Office",
                "Name": "Color Print",
                "Description": "Color Print",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0.2,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1414985663,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1362793433,
                "UpdatedOn": "2022-09-15T09:39:46Z",
                "CreatedOn": "2020-08-03T10:54:13Z",
                "UniqueId": "466a7333-997d-4013-8456-d8410422ed22",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Color Print (0.20 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Color Printing",
                "Description": "Printing for eZeep",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": 1,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415039629,
                "UpdatedOn": "2022-09-15T17:14:00Z",
                "CreatedOn": "2022-09-02T10:58:47Z",
                "UniqueId": "bbd887ff-b0c2-4110-8829-e7ed7eff3e8c",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Color Printing (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161924,
                "BusinessName": "Kalkio Network",
                "Name": "Day Pass",
                "Description": "A full day at Kalkio Space",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": "Day Passes",
                "DisplayOrder": 0,
                "Price": 10,
                "Visible": true,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1067467401,
                "ReducedTaxRateId": 1196519325,
                "ExemptTaxRateId": 1106436339,
                "FinancialAccountId": 1027679653,
                "AvailableAs": 3,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": true,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": "everyday-basics-GJY1eAw6tn8-unsplash.jpg",
                "ClearImageFile": false,
                "Id": 1004438439,
                "UpdatedOn": "2021-05-10T17:20:16Z",
                "CreatedOn": "2019-04-28T17:26:44Z",
                "UniqueId": "cb6207f1-c252-4bf2-8ca0-0e92740a4d2d",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": "DEMO",
                "ToStringText": "Day Pass (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Deposit",
                "Description": "A product used to charge deposits and retainer fees as part of a contract.",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 100,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1106436339,
                "ReducedTaxRateId": 1106436339,
                "ExemptTaxRateId": 1106436339,
                "FinancialAccountId": 1106398327,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1004440440,
                "UpdatedOn": "2022-03-03T11:59:05Z",
                "CreatedOn": "2019-04-28T17:26:43Z",
                "UniqueId": "e126f56c-4356-47b4-afa9-9338accfa45f",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": "DEMO",
                "ToStringText": "Deposit (100.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Deposits Premium",
                "Description": " ",
                "InvoiceLineDisplayAs": "Deposit",
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 500,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1414903755,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": -25,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415017328,
                "UpdatedOn": "2022-11-02T18:17:36Z",
                "CreatedOn": "2022-05-24T15:46:04Z",
                "UniqueId": "9185c30b-43f0-4fb5-bc31-01550e35f883",
                "UpdatedBy": "carlos+1004930927@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Deposits Premium (500.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Deposits Standard",
                "Description": " ",
                "InvoiceLineDisplayAs": "Deposit",
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1106398327,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": 1,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415017331,
                "UpdatedOn": "2022-09-15T17:14:00Z",
                "CreatedOn": "2022-05-24T16:29:34Z",
                "UniqueId": "0efaec2f-1e19-40f1-8660-82bb5f425302",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Deposits Standard (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Duplicated Test Product",
                "Description": "Duplicated Test Product",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3005,
                "CurrencyCode": "GBP",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": true,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415058800,
                "UpdatedOn": "2022-11-02T14:33:45Z",
                "CreatedOn": "2022-11-02T09:51:28Z",
                "UniqueId": "b01fa09e-ef75-4d6b-b515-9381cdf7de97",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Duplicated Test Product (0.00 GBP)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Incentive",
                "Description": "Incencive",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1414915776,
                "UpdatedOn": "2022-03-03T11:59:05Z",
                "CreatedOn": "2021-04-29T07:27:41Z",
                "UniqueId": "8e86ebc6-1ef7-422f-8b4a-1cf9f723e1c9",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Incentive (0.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Meeting Room Package",
                "Description": "Meeting Room Package",
                "InvoiceLineDisplayAs": "Meeting Room Package",
                "Sku": "",
                "Tags": "Benefits",
                "DisplayOrder": 0,
                "Price": 200,
                "Visible": true,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1196519325,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1027680654,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": 2,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": "s-o-c-i-a-l-c-u-t-1RT4txDDAbM-unsplash.jpg",
                "ClearImageFile": false,
                "Id": 1053321277,
                "UpdatedOn": "2022-09-22T17:52:58Z",
                "CreatedOn": "2019-06-05T12:00:33Z",
                "UniqueId": "c2182797-f7eb-49b3-837a-26c41323026e",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Meeting Room Package (200.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1240161924,
                "BusinessName": "Kalkio Network",
                "Name": "Network product",
                "Description": "another product away",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 10,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1414984953,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1414911424,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1414981689,
                "UpdatedOn": "2022-11-03T14:02:28Z",
                "CreatedOn": "2021-12-16T21:00:30Z",
                "UniqueId": "4ee7ec55-95f6-4f82-bc33-44b309a81b42",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Network product (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "PAYG",
                "Description": "test",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 10,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1414996717,
                "UpdatedOn": "2022-03-03T11:59:06Z",
                "CreatedOn": "2022-03-01T11:34:30Z",
                "UniqueId": "b3fe0a2f-1f4b-4f38-8d61-c8bd3d3ad413",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "PAYG (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Printing b&w",
                "Description": "Printin b&w",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0.15,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1414987971,
                "UpdatedOn": "2022-03-03T11:59:07Z",
                "CreatedOn": "2022-01-26T15:44:11Z",
                "UniqueId": "bd88fdc4-d16a-41f6-94c3-8d3ccb61135f",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Printing b&w (0.15 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Printing Color",
                "Description": "Printing color",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0.25,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": true,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": false,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1414988041,
                "UpdatedOn": "2022-03-03T11:59:08Z",
                "CreatedOn": "2022-01-26T15:43:43Z",
                "UniqueId": "00530ad8-1bdd-447c-b35b-9d75696c2e8a",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Printing Color (0.25 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Projector",
                "Description": "Projector - Meeting Room",
                "InvoiceLineDisplayAs": "Projector",
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 10,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1067467401,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1027680654,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": -1,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1006721716,
                "UpdatedOn": "2022-10-25T19:18:23Z",
                "CreatedOn": "2019-04-29T17:05:28Z",
                "UniqueId": "375d7552-4620-4e42-9717-eaa5f2890a40",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Projector (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Rent Discount",
                "Description": "Rent Discount",
                "InvoiceLineDisplayAs": null,
                "Sku": null,
                "Tags": null,
                "DisplayOrder": 0,
                "Price": 0,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3005,
                "CurrencyCode": "GBP",
                "TaxRateId": null,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 1,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": false,
                "AllowNegativeStock": true,
                "CurrentStock": null,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": false,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415051692,
                "UpdatedOn": "2022-10-17T15:16:41Z",
                "CreatedOn": "2022-10-17T15:16:41Z",
                "UniqueId": "9bb464be-f6a3-45fd-b741-2f6cf82a7c8d",
                "UpdatedBy": "adrian+1004930927@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Rent Discount (0.00 GBP)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Stationary",
                "Description": "Pens, pencils and paper for 1",
                "InvoiceLineDisplayAs": null,
                "Sku": "",
                "Tags": "Services",
                "DisplayOrder": 1,
                "Price": 10,
                "Visible": false,
                "SyncToSquare": false,
                "CurrencyId": 3004,
                "CurrencyCode": "USD",
                "TaxRateId": 1067467401,
                "ReducedTaxRateId": 1414985663,
                "ExemptTaxRateId": null,
                "FinancialAccountId": null,
                "AvailableAs": 3,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": false,
                "CurrentStock": 1,
                "StockAlertLevel": null,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": "lumensoft-technologies-pSz3JFTDZMA-unsplash.jpg",
                "ClearImageFile": false,
                "Id": 1011746754,
                "UpdatedOn": "2022-09-15T17:14:01Z",
                "CreatedOn": "2019-05-03T09:30:54Z",
                "UniqueId": "4ad2f462-24d4-4f8b-9f3f-bdf18e6bfd57",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Stationary (10.00 USD)",
                "LocalizationDetails": null,
                "CustomFields": null
            },
            {
                "BusinessId": 1004930927,
                "BusinessName": "Kalkio Space - East Side",
                "Name": "Stock Limit M4 Product",
                "Description": "M4 Products",
                "InvoiceLineDisplayAs": null,
                "Sku": "0",
                "Tags": "new",
                "DisplayOrder": 0,
                "Price": 10918,
                "Visible": true,
                "SyncToSquare": true,
                "CurrencyId": 3005,
                "CurrencyCode": "GBP",
                "TaxRateId": 1196519325,
                "ReducedTaxRateId": null,
                "ExemptTaxRateId": null,
                "FinancialAccountId": 1106398327,
                "AvailableAs": 3,
                "OnlyForContacts": false,
                "OnlyForMembers": false,
                "Tariffs": null,
                "AddedTariffs": null,
                "RemovedTariffs": null,
                "Archived": false,
                "Starred": false,
                "TrackStock": true,
                "AllowNegativeStock": true,
                "CurrentStock": -105,
                "StockAlertLevel": 0,
                "InvoiceCoworker": false,
                "SyncToNexKiosk": true,
                "NewImageUrl": null,
                "ImageFileName": null,
                "ClearImageFile": false,
                "Id": 1415044645,
                "UpdatedOn": "2022-09-28T15:08:11Z",
                "CreatedOn": "2022-09-15T12:59:06Z",
                "UniqueId": "443f89cd-7048-4053-9257-8fb146ceceb9",
                "UpdatedBy": "adrian+kalkio@nexudus.com",
                "IsNew": false,
                "SystemId": null,
                "ToStringText": "Stock Limit M4 Product (10918.00 GBP)",
                "LocalizationDetails": null,
                "CustomFields": null
            }
        ],
        "CurrentPageSize": 25,
        "CurrentPage": 1,
        "CurrentOrderField": "Name",
        "CurrentSortDirection": 0,
        "FirstItem": 1,
        "HasNextPage": true,
        "HasPreviousPage": false,
        "LastItem": 25,
        "PageNumber": 1,
        "PageSize": 25,
        "TotalItems": 32,
        "TotalPages": 2
    }
    let getToken = () => {
        let email = encodeURIComponent('adrian+1004930927@nexudus.com')
        let password = "iFMF5dr7Vz41"
        const options = {
            method: 'POST',
            headers: {
                accept: 'application/json',
                'Content-Type': 'application/x-www-form-urlencoded',
                'Access-Control-Allow-Origin': '*'
            },
            body: "grant_type=password&username=" + email + "&password=" + password
        };
        fetch('https://cors-anywhere.herokuapp.com/https://spaces.nexudus.com/api/token', options)
            .then(response => response.json())
            .then(response => {
                if (response.access_token !== null && response.access_token !== undefined) {
                    getProducts(response.access_token)
                }
            }
            )
            .catch(err => {
                setRecords(auxRecords.Records)
                console.error(err)
            });
    }

    let getProducts = (access_token) => {
        const options = {
            method: 'GET',
            headers: {
                authorization: 'Bearer ' + access_token
            }
        };

        fetch('https://cors-anywhere.herokuapp.com/https://spaces.nexudus.com/api/billing/products?page=1&size=25', options)
            .then(response => response.json())
            .then(response => {
                if (response.Records.length > 0) {
                    setRecords(response.Records)
                }
            })
            .catch(err => console.error(err));
    }

    useEffect(() => {
        getToken()
    }, [])
    return <>
        <Records records={records}></Records>
    </>
}

export default Fetcher;